### ISSUE TITLE
[Bug]: Authenticated/Not authenticated user state cached on every page

### ISSUE THREAD

**Issue by tbanys** [vuestorefront/redis-driver#4]
### Expected Behavior

In the header of storefront ui theme there is user icon which has autenticated/not authenticated states.

If the page was cached when user was not authenticated you will always see not authenticated state on first load or vice versa

### Actual Behavior

Cached pages should ignore user state and show current state of user state and not cached one.

### Steps to reproduce

1. Enable REDIS cache
2. Visit homepage (user not authenticated)
3. Authenticate user via login/register form
4. In the header you can see that user is authenticated (user authenticated)
5. Reload page
6. You will see that header shows cached user state (user not authenticated)

### What version of Magento 2 integration are you using?

Custom integration

### What version of Node.js are you using?

16.13.1

### What browser (and version) are you using?

Edge

### What operating system (and version) are you using?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
This package caches the whole SSR output. Like with any other type of cache, you must ensure that the cached page is not unique to a specific user and that it can be served to anyone.

To work around this, you can change how you load the data. You can load all generic data (like a catalog or product data) in `onSSR` (during Server-Side Rendering) and user-specific data in `onMounted` (in browser).

```diff
export default {
  setup () {
    const { load: loadProduct } = useProduct();
    const { load: loadUser } = useUser();
    const { load: loadWishlist } = useWishlist();

    onSSR(async () => {
      // Load generic-data during SSR
      await Promise.all([
        loadProduct({ id }),
-       loadUser(),
-       loadWishlist()
      ]);
    });

+   onMounted(async () => {
+     // load user-specific data in browser
+     await Promise.all([
+       loadUser(),
+       loadWishlist()
+     ]);
+   });
  }
};
```
